# Use the base Kafka image
FROM wurstmeister/kafka:2.12-2.3.0

# Add custom configuration files if needed
# COPY config/server.properties /opt/kafka/config/server.properties
# COPY kafka-run.sh /usr/bin/kafka-run.sh
# RUN chmod +x /usr/bin/kafka-run.sh

# Set entrypoint
# ENTRYPOINT ["/usr/bin/kafka-run.sh"]
